(function(){
  const bikeImage="electricbike.png", scooterImage="scooter.png";
  window.RIDE_CATALOG=[
    {id:"master-max",type:"bike",brand:"Kalofun",name:"MASTER MAX",subtitle:"שיכוך כפול, פאט 20×4 ומבנה מתקפל לרכיבות ארוכות.",batteryV:48,batteryAh:17.5,range:40,wheel:'20×4″',suspension:"מלא",folding:true,brakes:"הידראוליים",weight:"29.9 ק״ג",use:["מרחקים","שליחויות","נוחות"],badge:"דגם דגל",image:bikeImage,fit:"לרוכבים שמבקשים נוחות גבוהה, אחיזה ונשיאת ציוד לאורך יום שימוש.",highlights:["שלדת אלומיניום 6061","6 הילוכי Shimano","מזלג MOZO"],source:"https://kalofun.co.il/product/%D7%90%D7%95%D7%A4%D7%A0%D7%99%D7%99%D7%9D-%D7%97%D7%A9%D7%9E%D7%9C%D7%99%D7%99%D7%9D-%D7%9E%D7%90%D7%A1%D7%98%D7%A8-%D7%9E%D7%A7%D7%A1-master-max-%D7%A9%D7%97%D7%95%D7%A8-%D7%9C%D7%91%D7%9F/"},
    {id:"big-dog-roadstar",type:"bike",brand:"GreenBike",name:"BIG Dog RoadStar",subtitle:"מיני־פאט מתקפל עם סוללת Samsung ובלימה הידראולית.",batteryV:48,batteryAh:15,range:70,wheel:'20×4″',suspension:"קדמי",folding:true,brakes:"הידראוליים",weight:"27 ק״ג",use:["עיר","מרחקים","אחסון"],badge:"מיני פאט",image:bikeImage,fit:"שילוב שימושי בין גלגל רחב, קיפול וטווח יצרן ארוך לרכיבה עירונית.",highlights:["כושר נשיאה 110 ק״ג","6 הילוכי Shimano","חישוקי סגסוגת"],source:"https://greenbike.biz/product/%D7%90%D7%95%D7%A4%D7%A0%D7%99%D7%99%D7%9D-%D7%97%D7%A9%D7%9E%D7%9C%D7%99%D7%99%D7%9D-big-dog-%D7%9E%D7%99%D7%A0%D7%99-%D7%A4%D7%98/"},
    {id:"legend",type:"bike",brand:"GreenBike",name:"Legend",subtitle:"מבנה מתקפל, גלגלי 20 אינץ׳ ובלימה הידראולית ליום־יום.",batteryV:48,batteryAh:15,range:70,wheel:'20×4″',suspension:"קדמי",folding:true,brakes:"הידראוליים",weight:"25 ק״ג",use:["עיר","שליחויות","מרחקים"],badge:"אורבני",image:bikeImage,fit:"למי שמחפש כלי יום־יומי קשיח עם תנוחת רכיבה מוכרת ואחסון גמיש.",highlights:["כושר נשיאה 110 ק״ג","6 הילוכי Shimano","צג LCD"],source:"https://greenbike.biz/product/legend-hd/"},
    {id:"city-path-low",type:"bike",brand:"GreenBike",name:"City Path Low",subtitle:"שלדת Step Through נמוכה, פאט 20×4 ומושב אחורי.",batteryV:48,batteryAh:15,range:70,wheel:'20×4″',suspension:"קדמי",folding:true,brakes:"הידראוליים",weight:"28 ק״ג",use:["נוחות","עיר","שליחויות"],badge:"שלדה נמוכה",image:bikeImage,fit:"לעלייה וירידה קלות יותר, תנוחה זקופה ונסיעות עירוניות עם ציוד.",highlights:["כושר נשיאה 120 ק״ג","צג M5 צבעוני","בלמי XOD E700"],source:"https://greenbike.biz/product/%D7%90%D7%95%D7%A4%D7%A0%D7%99-city-path-4%E2%80%B3-%D7%A1%D7%99%D7%98%D7%99-%D7%A4%D7%90%D7%98-4%E2%80%B3-%D7%A9%D7%9C%D7%93%D7%94-%D7%A0%D7%9E%D7%95%D7%9B%D7%94/"},
    {id:"city-path-mini",type:"bike",brand:"GreenBike",name:"CITY PATH MINI FAT",subtitle:"מיני־פאט מתקפל עם גלגל 20×3 ובלימה הידראולית.",batteryV:48,batteryAh:16,range:70,wheel:'20×3″',suspension:"קדמי",folding:true,brakes:"הידראוליים",weight:"—",use:["עיר","נוחות","אחסון"],badge:"חדש",image:bikeImage,fit:"למי שרוצה תחושת פאט פחות כבדה, שלדה נגישה וקיפול לאחסון.",highlights:["כושר נשיאה 110 ק״ג","6 הילוכי Shimano","שלדת אלומיניום 6061"],source:"https://greenbike.biz/product/%D7%90%D7%95%D7%A4%D7%A0%D7%99%D7%99%D7%9D-%D7%97%D7%A9%D7%9E%D7%9C%D7%99%D7%99%D7%9D-city-path-mini-fat/"},
    {id:"city-premium",type:"bike",brand:"GreenBike",name:"City Premium",subtitle:"דגם עירוני קלאסי עם סוללה נשלפת וחישוקי מגנזיום.",batteryV:36,batteryAh:10.4,range:null,wheel:'20″',suspension:"קדמי",folding:false,brakes:"מכניים",weight:"—",use:["עיר","קלות","נוחות"],badge:"עירוני",image:bikeImage,fit:"לנסיעות קצרות־בינוניות בעיר, תנוחה נוחה ותחזוקה פשוטה.",highlights:["סוללה נשלפת עם מנעול","חיווט בתוך השלדה","מנוע HT ללא פחמים"],source:"https://greenbike.biz/electric-bikes/"},
    {id:"xiaomi-scooter-4",type:"scooter",brand:"Xiaomi",name:"Electric Scooter 4",subtitle:"כלי אורבני מאוזן עם צמיגי 10 אינץ׳, BMS ובלימה כפולה.",batteryV:36,batteryAh:7.65,range:35,wheel:'10″',suspension:"ללא",folding:true,brakes:"E-ABS + דיסק",weight:"17.2 ק״ג",use:["עיר","קלות","אחסון"],badge:"עירוני",image:scooterImage,fit:"למסלול עירוני יומי, נשיאה מזדמנת ושילוב עם תחבורה ציבורית.",highlights:["IP54","אפליקציית Mi Home","משטח דריכה 16 ס״מ"],source:"https://www.mi-il.co.il/product/xiaomi-electric-scooter-4-eu"},
    {id:"inokim-quick-4",type:"scooter",brand:"INOKIM",name:"Quick 4",subtitle:"סוללת 52V, טווח יצרן ארוך והנעה אחורית.",batteryV:52,batteryAh:16,range:50,wheel:'10″',suspension:"מלא",folding:true,brakes:"תוף",weight:"21.5 ק״ג",use:["מרחקים","נוחות","עיר"],badge:"פרימיום",image:scooterImage,fit:"למי שנוסע מרחקים ארוכים יותר ורוצה רזרבת סוללה ונוחות.",highlights:["הנעה אחורית","טעינה כ־7 שעות","מבנה מתקפל"],source:"https://il.inokim.com/products/inokim-quick-4/overview"},
    {id:"segway-max-g30",type:"scooter",brand:"Segway",name:"Ninebot MAX G30",subtitle:"טווח יצרן עד 65 ק״מ, צמיגי 10 אינץ׳ וקיפול בלחיצה.",batteryV:36,batteryAh:15.3,range:65,wheel:'10″',suspension:"ללא",folding:true,brakes:"תוף + חשמלי",weight:"19.1 ק״ג",use:["מרחקים","עיר","אמינות"],badge:"טווח",image:scooterImage,fit:"לנסיעות עירוניות ארוכות יחסית, עם דגש על פשטות וטווח.",highlights:["שלושה מצבי רכיבה","צמיגי ג׳ל","הנעה אחורית"],source:"https://www.segwayisrael.com/product/my-segway-max/"},
    {id:"icon-11",type:"scooter",brand:"GreenBike",name:"ICON 11",subtitle:"גלגלי 11 אינץ׳, מערכת איתותים וסוללת 48V.",batteryV:48,batteryAh:12.5,range:50,wheel:'11″',suspension:"קדמי",folding:true,brakes:"דיסק כפול",weight:"17.5 ק״ג",use:["נוחות","עיר","מרחקים"],badge:"11 אינץ׳",image:scooterImage,fit:"למי שמעדיף גלגל גדול יותר ושיכוך טוב יותר של מפגעי דרך קטנים.",highlights:["כושר נשיאה 100 ק״ג","מערכת איתותים","צג צבעוני"],source:"https://greenbike.biz/product/%D7%A7%D7%95%D7%A8%D7%A7%D7%99%D7%A0%D7%98-%D7%97%D7%A9%D7%9E%D7%9C%D7%99-icon-11-48v-12-5ah/"},
    {id:"king-pro",type:"scooter",brand:"GreenBike",name:"KING PRO",subtitle:"סוללת 48V/21Ah, בלמים הידראוליים ומבנה קשיח.",batteryV:48,batteryAh:21,range:40,wheel:'10×2.75″',suspension:"מלא",folding:true,brakes:"הידראוליים",weight:"25 ק״ג",use:["מרחקים","נוחות","שליחויות"],badge:"סוללה גדולה",image:scooterImage,fit:"לשימוש תדיר עם דגש על קיבולת, בלימה ונוכחות כביש.",highlights:["שלדת אלומיניום 6061","צג צבעוני","כושר נשיאה 100 ק״ג"],source:"https://greenbike.biz/product/%D7%A7%D7%95%D7%A8%D7%A7%D7%99%D7%A0%D7%98-%D7%97%D7%A9%D7%9E%D7%9C%D7%99-king-pro-48v-21ah/"},
    {id:"king",type:"scooter",brand:"GreenBike",name:"KING",subtitle:"48V, גלגלי 10 אינץ׳ ומערכת דיסק קדמית ואחורית.",batteryV:48,batteryAh:15.6,range:40,wheel:'10×2.75″',suspension:"מלא",folding:true,brakes:"דיסק כפול",weight:"25 ק״ג",use:["עיר","נוחות","מרחקים"],badge:"מאוזן",image:scooterImage,fit:"כלי ביניים מאוזן בין קיבולת, נוחות, משקל ומחיר שוק.",highlights:["שלדת אלומיניום 6061","3 מצבי רכיבה","צג צבעוני"],source:"https://greenbike.biz/product/%D7%A7%D7%95%D7%A8%D7%A7%D7%99%D7%A0%D7%98-%D7%97%D7%A9%D7%9E%D7%9C%D7%99-king-48v-15-6ah/"},
    {id:"icon-10",type:"scooter",brand:"GreenBike",name:"ICON 10",subtitle:"כלי קל יחסית עם אפליקציה, איתותים ומשטח עץ רחב.",batteryV:36,batteryAh:10,range:35,wheel:'8.5×2.5″',suspension:"ללא",folding:true,brakes:"חשמלי + דיסק",weight:"14.5 ק״ג",use:["קלות","עיר","אחסון"],badge:"קל",image:scooterImage,fit:"למי שמעלה את הכלי הביתה או משלב רכבת ואוטובוס.",highlights:["אפליקציית שליטה","מערכת איתותים","כושר נשיאה 90 ק״ג"],source:"https://greenbike.biz/product/%D7%A7%D7%95%D7%A8%D7%A7%D7%99%D7%A0%D7%98-%D7%97%D7%A9%D7%9E%D7%9C%D7%99-icon-10-36v-10-4ah/"},
    {id:"punk-rider",type:"scooter",brand:"GreenBike",name:"Punk Rider",subtitle:"עיצוב נוכח, תאורה היקפית, אפליקציה ובלימה רגנרטיבית.",batteryV:48,batteryAh:15.6,range:65,wheel:'10×2.7″',suspension:"מלא",folding:true,brakes:"תוף + רגנרטיבי",weight:"26–27 ק״ג",use:["מרחקים","נוחות","טכנולוגיה"],badge:"טכנולוגי",image:scooterImage,fit:"למי שרוצה נראות, תאורה, אפליקציה וטווח יצרן גבוה במצב ECO.",highlights:["תאורה היקפית","צפצפה מובנית","כושר נשיאה 120 ק״ג"],source:"https://greenbike.biz/product/%D7%A7%D7%95%D7%A8%D7%A7%D7%99%D7%A0%D7%98-%D7%97%D7%A9%D7%9E%D7%9C%D7%99-punk-rider/"}
  ];
  const commerce={
    "master-max":{price:5999,stock:true},
    "big-dog-roadstar":{price:4190,oldPrice:4990,stock:true},
    "legend":{price:4090,oldPrice:4590,stock:true},
    "city-path-low":{price:5890,oldPrice:6200,stock:true},
    "city-path-mini":{price:4190,oldPrice:5290,stock:true},
    "city-premium":{price:4280,stock:true},
    "xiaomi-scooter-4":{price:2249,stock:false},
    "inokim-quick-4":{price:null,stock:false},
    "segway-max-g30":{price:null,stock:false},
    "icon-11":{price:2990,oldPrice:3290,stock:true},
    "king-pro":{price:4390,oldPrice:4790,stock:true},
    "king":{price:3890,oldPrice:4190,stock:true},
    "icon-10":{price:1890,oldPrice:2190,stock:true},
    "punk-rider":{price:3790,oldPrice:5090,stock:true}
  };
  window.RIDE_CATALOG.forEach(item=>Object.assign(item,{price:null,oldPrice:null,stock:false},commerce[item.id]||{}));
})();
